version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app  # Cho phép hot-reload trong quá trình phát triển
      - ./data:/app/data  # Volume cho dữ liệu
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - DEBUG=True
    depends_on:
      - qdrant
    restart: unless-stopped
    command: ["--host", "0.0.0.0", "--port", "8000", "--reload"]  # Chế độ reload cho phát triển

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"  # Dashboard của Qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data:
    driver: local 