version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: database_eyevi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: eyevi_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis_eyevi
    restart: always
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --requirepass 123456 --appendonly no